### ISSUE TITLE
Docs: Syntax highlighting colors seem to be inconsistent across targets

### ISSUE THREAD

**Issue by Soroosh129** [lf-lang/website-lingua-franca#45]
**Page URL:** 
docs/handbook/composing-reactors

**Issue:** 
The coloring in the syntax highlighting seems to be inconsistent at times.

Examples:

![image (6)](https://user-images.githubusercontent.com/4221770/165657668-0797cfa3-f3b9-417b-a436-185d45467e7a.png)
![image (5)](https://user-images.githubusercontent.com/4221770/165657669-c3e87ebf-5aed-4f6d-ad33-6568518831db.png)
![image (3)](https://user-images.githubusercontent.com/4221770/165657671-ffad64b1-425e-4b84-b886-cb9508fe901f.png)
![image (4)](https://user-images.githubusercontent.com/4221770/165657670-33127b00-6d97-4ed6-b25d-2ff954ee0a72.png)

**Recommended Fix:**

**Comment by edwardalee** [comment]
I think this has been fixed by using @petervdonovan 's language-specific highlighting.
