### ISSUE TITLE
Colors in menu are weird

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/website-lingua-franca#49]
While the colors weren't optimal in the first place, they are now rather weird, particularly in the dark theme. I think the change was brought about in this commit: https://github.com/lf-lang/website-lingua-franca/commit/1ded45c67aa29f8bf3798632a45495540dfbe16b, but I'm not sure.

**Comment by petervdonovan** [comment]
Should this have been closed by #85? I never understood exactly what this issue referred to.

**Comment by lhstrh** [comment]
It has been fixed, yes.
