### ISSUE TITLE
LF Code Syntax Highlighting for Handbook

### ISSUE THREAD

**Issue by arengarajan99** [lf-lang/website-lingua-franca#5]
**Improvement Idea:** Implementing Code Syntax Highlighting for Lingua Franca Code Snippets using PrismJS

**Why:** VS Code already implements Code Syntax Highlighting for .lf files. [Remark-PrismJS](https://www.gatsbyjs.com/plugins/gatsby-remark-prismjs/) is the standard Gatsby Plugin used to highlight code on Gatsby websites, and it's possible to create a [custom language](https://prismjs.com/extending.html) that Prism can process for code snippets

**Comment by petervdonovan** [comment]
This should be addressed by #11.
