### ISSUE TITLE
LF keyword highlighting does not match in text and code

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/website-lingua-franca#57]
With the use of the LSP syntax highlighting, the LF keywords in code blocks no longer match the LF keywords in the text. I had previously had LF keywords in bold and what I've been calling "Lingua Franca orange", which is the orange in the logo. Currently, that is what we have in the text. In the code blocks, we have light blue (which should probably be darker in light mode) and not bold. In the C bodies, functions are bold and have a color that looks a bit like LF orange, but not quite.  Maybe the functions should be bold blue and the LF keywords should be bold orange?

**Comment by petervdonovan** [comment]
I agree that we did lose something. The orange is distinctive and memorable. My only concern is that orange is a strong/opinionated color in comparison to blue, which makes me worry about having too much orange:

<img alt="Screenshot from 2022-05-04 14-29-35" src="https://user-images.githubusercontent.com/33707478/166829019-c8c73cff-a35d-4385-bbda-b848041879c7.png" width="70%">

There is also perhaps a bad interaction with the purple, and the fact that LF orange is akin to the orange for numeric literals, but not quite the same... In any case, I have no strong opinion on the matter (the original colors that I picked were just a cheap replica of a [VS Code theme](https://github.com/microsoft/vscode/blob/main/extensions/theme-quietlight/themes/quietlight-color-theme.json)), and it is an easy change in `packages/lingua-franca/src/style/code.scss`.

**Comment by lhstrh** [comment]
Would it be worth customizing it like we do with the fonts and theme already? This obviously won't work for the PDFs, but at the very least we can make the keyword color match the colors being used in the text...

**Comment by lhstrh** [comment]
BTW, I share the concern about too much orange... Maybe we should do some mock ups using Figma to figure out what works well...

**Comment by edwardalee** [comment]
I'm confused about `packages/lingua-franca/src/style/code.scss`.  I discovered by trial and error that to control the color of the LF keywords, I have to modify `keyword-control` and `storage-modifier`. The first changes some of the keywords, and the second seems to change a few more.  Is there any rationality to the names of these classes? Where are they defined?

**Comment by edwardalee** [comment]
The colors in the text and code snippets now match, so I'm closing this issue.

**Comment by lhstrh** [comment]
It's a little hard to keep track of what's happening in the repository this way. Which commits were or which PR was responsible for making the text and code snippets match?

**Comment by edwardalee** [comment]
Commit 7fd1fc3fdd8a29e6e5be2cf6a625b0d160e19d6f is the one that set the colors.
