### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/website-lingua-franca#59]
There are number of dead links that I'm not sure how to deal with:

In `packages/lingua-franca/src/templates/pages/publications-and-presentations.tsx`, there are pointers to a number of "assets" (mostly in the presentations section) that do not exist.  Anyone know where these are?  The problems are these:
- https://www.lf-lang.org/publications-and-presentations/assets/slides/Lohstroh_etAl_CyPhy19.pdf 
- https://www.lf-lang.org/publications-and-presentations/assets/slides/Lohstroh_etAl_EMSOFT19.pdf
- https://www.lf-lang.org/publications-and-presentations/assets/slides/Lohstroh_Lee_FDL19.pdf
- https://www.lf-lang.org/publications-and-presentations/assets/slides/Lee_ActorsRevisited_CyPhy.pdf
- https://www.lf-lang.org/publications-and-presentations/assets/slides/Lohstroh_etAl_FDL20.pdf

In `packages/lingua-franca/src/components/layout/fonts.scss` there are URLs for the following fonts that all yield 404s:
- leelawadeeui-light.woff2
- leelawadeeui-light.woff
- leelawadeeui-semibold.woff2
- leelawadeeui-semibold.woff

There are also a number of dead links in the Distributed Execution page, but this page needs a complete overhaul, so I'm not worried about those yet.

You can check for dead links using this website: https://www.deadlinkchecker.com/website-dead-link-checker.asp

**Comment by lhstrh** [comment]
They are here: https://github.com/lf-lang/website-lingua-franca/tree/main/packages/lingua-franca/static/assets/slides
