### ISSUE TITLE
[Handbook] Add link to submit a pull request to improve each page

### ISSUE THREAD

**Issue by Soroosh129** [lf-lang/website-lingua-franca#74]
Suggested by @edwardalee.

Each page of the handbook should have a link to the corresponding GitHub page so that readers can suggest improvements to that page in the form of a pull request.

For example, the [troubleshooting](https://www.lf-lang.org/docs/handbook/troubleshooting) page has the following text:

> If you have suggestions for additions to this page, please [submit a pull request](https://github.com/lf-lang/website-lingua-franca/blob/main/packages/documentation/copy/en/tools/Troubleshooting.md).

This could be included in the footer or side bar of each page. For example [GitHub docs](https://docs.github.com/en) has this in the footer of every page:
![image](https://user-images.githubusercontent.com/4221770/174164058-a184d643-6991-4933-a854-33e950f5d789.png)
Clicking on the provided link will bring you directly to the edit mode of that page. For example, the homepage link will get you to https://github.com/github/docs/edit/main/content/index.md (note the `edit` word in the link). GitHub will then guide you through the process to edit this page. If it requires creating a fork, GitHub will guide you through that process all on the web.  This is a nice built-in feature of GitHub that would make it easy to suggest improvements for each handbook page.  For example, here is a direct link to modify the "A First Reactor" page:
https://github.com/lf-lang/website-lingua-franca/edit/main/packages/documentation/copy/en/topics/A%20First%20Reactor.md

**Comment by lhstrh** [comment]
I'm a bit confused. We have this (screen grab from the troubleshooting page you mention):

![image](https://user-images.githubusercontent.com/19938940/174231425-d8787a44-a9bd-4d07-81d8-afd9f6842c84.png)

Doesn't this do exactly what you describe?

**Comment by Soroosh129** [comment]
Oh, you're right! Somehow we missed that. Thanks :)
