### ISSUE TITLE
Color scheme: Purge #3178c6

### ISSUE THREAD

**Issue by petervdonovan** [lf-lang/website-lingua-franca#75]
I mean this shade of blue:

![TypeScript](https://user-images.githubusercontent.com/33707478/174415115-9292934f-9410-4856-94cf-e374645f381f.png)

This color already "belongs" to TypeScript: It's recognizably a TS color.

I'm posting this as an issue rather than trying to solve it myself because I do think it is a little complicated and important. To my knowledge, LF has specific shades of orange and dark blue, respectively, but no light blue. We could add another color, but maybe that would be excessive. And if we restrict ourselves to the existing colors, which are too strong and dark to use in large quantities, then our front page might require some redesign.

**Comment by edwardalee** [comment]
I've been using Berkeley colors for everything.  See https://brand.berkeley.edu/colors/

The TypeScript blue looks a lot like the Berkeley "founder's rock".
